# Generated by Django 5.1.7 on 2025-03-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('descripcion', models.CharField(max_length=2000)),
                ('imageurl', models.CharField(max_length=120)),
                ('pregunta', models.CharField(max_length=2000)),
                ('respuesta', models.CharField(max_length=2000)),
            ],
        ),
    ]
