# Generated by Django 5.1.7 on 2025-03-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imageurl',
            field=models.CharField(max_length=500),
        ),
    ]
