# Generated by Django 5.1.6 on 2025-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='bloqueada',
            field=models.BooleanField(default=True),
        ),
    ]
