# Generated by Django 5.1.7 on 2025-03-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_imagen_bloqueada'),
        ('bio', '0003_alter_imagen_imageurl'),
    ]

    operations = [
    ]
