# Generated by Django 5.1.7 on 2025-04-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_alter_imagen_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=2000)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
