# Generated by Django 5.1.7 on 2025-05-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
