# Generated by Django 5.1.7 on 2025-05-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0007_alter_registro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='opcion1',
            field=models.CharField(default='valor', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen',
            name='opcion2',
            field=models.CharField(default='algo', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen',
            name='opcion3',
            field=models.CharField(default='algo', max_length=2000),
            preserve_default=False,
        ),
    ]
