# Generated by Django 5.1.7 on 2025-05-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0009_imagendesbloqueada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
